name: Daily Chess Report

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch: 

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Download Stockfish
        run: |
          wget https://stockfishchess.org/files/stockfish_15.1_linux_x64_avx2.zip
          unzip stockfish_15.1_linux_x64_avx2.zip
          chmod +x stockfish_15.1_linux_x64_avx2/stockfish_15.1_linux_x64_avx2
      - name: Run analysis
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py 